=== MartinM2304/XML/HR.dtd
<!ELEMENT hr_catalogue (groups+)>

<!ELEMENT groups (group+)>

<!ELEMENT group (subgroup+)>
<!ATTLIST group id ID #REQUIRED>
<!ATTLIST group name CDATA #REQUIRED> 

<!ELEMENT subgroup (employee+)>
<!ATTLIST subgroup id ID #REQUIRED>
<!ATTLIST subgroup name CDATA #REQUIRED> 
<!ATTLIST subgroup groupRef IDREF #REQUIRED>

<!ELEMENT employee (photo?,rank,employment,gallery?,personal_data,skills)>
<!ATTLIST employee id ID #REQUIRED>
<!ELEMENT photo (#PCDATA)>
<!ELEMENT rank (#PCDATA)>
<!ELEMENT employment (#PCDATA)>
<!ATTLIST employment type CDATA #REQUIRED>
<!ELEMENT gallery (image)>
<!ELEMENT image (#PCDATA)>
<!ATTLIST image source CDATA #REQUIRED>
<!ELEMENT skills (skill*)>
<!ELEMENT skill (#PCDATA)>

<!ELEMENT personal_data (name,age,experience,salary)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT age (#PCDATA)>
<!ELEMENT experience (#PCDATA)>
<!ELEMENT salary (#PCDATA)>

=== MartinM2304/XML/HR.xml
<?xml version="1.0" encoding="UTF-8"?>

<?xml-stylesheet type = "text/xsl" href = "HR.xsl"?>

<!DOCTYPE hr_catalogue SYSTEM "HR.dtd" [
	<!ATTLIST hr_catalogue
		xmlns:xsi CDATA #FIXED "http://www.w3.org/2001/XMLSchema-instance"
		xsi:noNamespaceSchemaLocation CDATA #FIXED "HR_Catalogue_schema.xsd">]>
		
<hr_catalogue xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="HR_Catalogue_schema.xsd">
	<groups>
		<group id="G1" name="Development">
			<subgroup id="S1.1" groupRef="G1" name="Frontend">
				<employee id="DF001">
					<photo>resources/martin_marinkov.jpg</photo>
					<rank>Senior</rank>
					<employment type="full-time" />

					<gallery>
						<image source="image1" />
					</gallery>

					<personal_data>
						<name>Martin Marinkov</name>
						<age>20</age>
						<experience>2</experience>
						<salary>10000</salary>
					</personal_data>

					<skills>
						<skill>C++</skill>
						<skill>C</skill>
						<skill>Java</skill>
						<skill>XML</skill>
					</skills>
				</employee>

				<employee id="DF002">
					
					<photo>resources/kristian_petrov.jpg</photo>
					<rank>Senior</rank>
					<employment type="part-time" />

					<personal_data>
						<name>Kristian Petrov</name>
						<age>21</age>
						<experience>2</experience>
						<salary>10000</salary>
					</personal_data>

					<skills>
						<skill>C++</skill>
						<skill>JavaScript</skill>
						<skill>Java</skill>
						<skill>Python</skill>
					</skills>
				</employee>
			</subgroup>

			<subgroup id="S1.2" groupRef="G1" name="BackEnd">
				<employee id="DB002"> <!-- Development backend 02-->
					<photo>resources/alex_vasquez.jpg</photo>
					<rank>Junior</rank>
					<employment type="part-time" />

					<personal_data>
						<name>Alex Vasquez</name>
						<age>31</age>
						<experience>12</experience>
						<salary>9000</salary>
					</personal_data>

					<skills>
						<skill>TypeScript</skill>
						<skill>JavaScript</skill>
						<skill>App design</skill>
						<skill>Web developer</skill>
					</skills>
				</employee>

				<employee id="DB003"> 
					<photo>resources/boian_todorv.jpg</photo>
					<rank>Junior</rank>
					<employment type="part-time" />

					<personal_data>
						<name>Boyan Todorov</name>
						<age>22</age>
						<experience>2</experience>
						<salary>2200</salary> 
					</personal_data>

					<skills>
						<skill>C++</skill>
						<skill>Bash</skill>
						<skill>Python</skill>
					</skills>
				</employee>

			</subgroup>

		</group>

		<group id="G2" name="Marketing">
			<subgroup id="S2.1" groupRef="G2" name="Social Marketing">
				<employee id="MS001"> <!-- Marketing _ 01-->
					<photo>resources/Ecom_Success.jpg</photo>
					<rank>Intern</rank>
					<employment type="full-time" />

					<personal_data>
						<name>Ecom Success</name>
						<age>30</age>
						<experience>8</experience>
						<salary>12000</salary>
					</personal_data>

					<skills>
						<skill>Marketing Strategy</skill>
						<skill>Product Management</skill>
					</skills>
				</employee>
			</subgroup>
			<subgroup id="S2.2" groupRef="G2" name="Content Marketing">
				<employee id="MC002"> <!-- Marketing _ 01-->
					<photo>resources/abdul_raheem.jpg</photo>
					<rank>Intern</rank>
					<employment type="full-time" />

					<personal_data>
						<name>Abdul Raheem</name>
						<age>33</age>
						<experience>11</experience>
						<salary>8000</salary>
					</personal_data>

					<skills>
						<skill>Content Management</skill>
						<skill>Marketing Strategy</skill>
						<skill>Product Management</skill>
					</skills>
				</employee>
			</subgroup>
		</group>

		<group id="G3" name="Sales">
			<subgroup id="S3.1" groupRef="G3" name="Customer Sales">
				<employee id="SC04">
					<photo>resources/kaffla_imran.jpg</photo>
					<rank>Senior</rank>
					<employment type="full-time" />

					<personal_data>
						<name>Kaffla Imran</name>
						<age>40</age>
						<experience>5</experience>
						<salary>15000</salary>
					</personal_data>

					<skills>
						<skill>Negotiation</skill>
						<skill>Creativity</skill>
						<skill>Stubbornness</skill>
						<skill>Team Work</skill>
					</skills>
				</employee>
			</subgroup>
			<subgroup id="S3.2" groupRef="G3" name="Business Sales">
				<employee id="SB06">
					<photo>resources/Enzo_morana.jpg</photo>
					<rank>Mid</rank>
					<employment type="part-time" />

					<personal_data>
						<name>Enzo Morana</name>
						<age>30</age>
						<experience>2</experience>
						<salary>5000</salary>
					</personal_data>

					<skills>
						<skill>Negotiation</skill>
						<skill>Domain Knowledge</skill>
						<skill>Hard Working</skill>
						<skill>Team Work</skill>
					</skills>
				</employee>
			</subgroup>
		</group>
	</groups>

</hr_catalogue>
